# Exploratory Data Analysis

Tokyo - (35,140)  
Jakarta - (-7, 112)  
Brisbane - (-27, 153)

- Opening the zip file and checking the contents

In [1]:
import zipfile
import os

# list all the files in RE_data.zip
with zipfile.ZipFile('RE_data.zip', 'r') as zip_ref:
    zip_ref.extractall('.')
    for file in zip_ref.namelist():
        print(file)
os.remove('RE_data.zip')

1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1980.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1981.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1982.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1983.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1984.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1985.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1986.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1987.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1988.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1989.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1990.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1991.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1992.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1993.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1994.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1995.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1996.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1997.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1998.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_1999.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2000.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2001.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2002.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2003.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2004.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2005.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2006.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2007.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2008.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2009.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2010.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2011.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2012.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2013.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2014.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2015.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2016.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2017.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2018.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2019.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2020.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2021.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2022.csv
1980-2023 renewable energy data/ninja_pv_-27.4665_153.0260_2023.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1980.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1981.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1982.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1983.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1984.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1985.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1986.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1987.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1988.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1989.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1990.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1991.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1992.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1993.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1994.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1995.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1996.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1997.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1998.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_1999.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2000.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2001.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2002.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2003.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2004.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2005.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2006.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2007.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2008.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2009.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2010.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2011.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2012.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2013.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2014.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2015.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2016.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2017.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2018.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2019.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2020.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2021.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2022.csv
1980-2023 renewable energy data/ninja_pv_35.2474_140.4001_2023.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1980.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1981.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1982.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1983.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1984.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1985.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1986.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1987.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1988.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1989.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1990.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1991.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1992.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1993.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1994.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1995.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1996.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1997.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1998.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1999.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2000.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2001.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2002.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2003.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2004.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2005.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2006.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2007.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2008.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2009.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2010.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2011.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2012.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2013.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2014.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2015.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2016.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2017.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2018.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2019.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2020.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2021.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2022.csv
1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2023.csv

In [3]:
import pandas as pd

# checking one of the files
data = pd.read_csv('1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_2023.csv', header=3)
data

                  time        local_time  electricity
0     2023-01-01 00:00  2023-01-01 07:00      164.424
1     2023-01-01 01:00  2023-01-01 08:00      288.349
2     2023-01-01 02:00  2023-01-01 09:00      395.998
3     2023-01-01 03:00  2023-01-01 10:00      473.978
4     2023-01-01 04:00  2023-01-01 11:00      507.299
...                ...               ...          ...
8755  2023-12-31 19:00  2024-01-01 02:00        0.000
8756  2023-12-31 20:00  2024-01-01 03:00        0.000
8757  2023-12-31 21:00  2024-01-01 04:00        0.000
8758  2023-12-31 22:00  2024-01-01 05:00        3.587
8759  2023-12-31 23:00  2024-01-01 06:00       53.769

[8760 rows x 3 columns]

- Collecting the data for Jakarta from 1981-2023 and saving it in a big dataframe
- Not considering the data from 1980 as a few intial values are missing

In [15]:
# Jakarta 

data_jakarta = pd.read_csv('1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_1980.csv', header=3)
name = "1980-2023 renewable energy data/ninja_pv_-7.2623_112.7361_"

for i in range(1981, 2024):
    data_jakarta = pd.concat([data_jakarta, pd.read_csv(name + str(i) + '.csv', header=3)])

data_jakarta.drop(columns=['time'], inplace=True)
data_jakarta['local_time'] = pd.to_datetime(data_jakarta['local_time'])

print("Info:\n", data_jakarta.info())
print("Head:\n", data_jakarta.head())
print("Tail:\n", data_jakarta.tail())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 385704 entries, 0 to 8759
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   local_time   385704 non-null  datetime64[ns]
 1   electricity  385704 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 8.8 MB
Info:
 None
Head:
            local_time  electricity
0 1980-01-01 07:00:00      178.383
1 1980-01-01 08:00:00      282.887
2 1980-01-01 09:00:00      366.623
3 1980-01-01 10:00:00      429.596
4 1980-01-01 11:00:00      443.867
Tail:
               local_time  electricity
8755 2024-01-01 02:00:00        0.000
8756 2024-01-01 03:00:00        0.000
8757 2024-01-01 04:00:00        0.000
8758 2024-01-01 05:00:00        3.587
8759 2024-01-01 06:00:00       53.769

## Average for Every Month for Every Year

- Converting the data to calculate the average kW for every month for every year.

In [23]:
monthly_means = {}

for month in range(1,13):
    for hour in range(24):
        monthly_means[(month, hour)] = [data_jakarta[(data_jakarta['local_time'].dt.year == year) & (data_jakarta['local_time'].dt.month == month) & (data_jakarta['local_time'].dt.hour == hour)]['electricity'].mean() for year in range(1981, 2024)]

monthly_means = pd.DataFrame(monthly_means, index=range(1981, 2024))

print("Monthly means:\n", monthly_means)

Monthly means:
        1                                                                      \
       0    1    2    3    4          5           6           7           8
1981  0.0  0.0  0.0  0.0  0.0  13.554581  112.441774  237.408774  348.555516
1982  0.0  0.0  0.0  0.0  0.0  16.494387  138.053000  291.210839  418.658194
1983  0.0  0.0  0.0  0.0  0.0  24.469452  168.826968  313.077968  426.619194
1984  0.0  0.0  0.0  0.0  0.0  14.537161  121.603677  256.989516  370.498903
1985  0.0  0.0  0.0  0.0  0.0  31.068581  190.038355  352.806613  466.454452
1986  0.0  0.0  0.0  0.0  0.0  15.098710  125.375645  263.999000  378.191097
1987  0.0  0.0  0.0  0.0  0.0  12.777548  105.707484  232.394258  353.914452
1988  0.0  0.0  0.0  0.0  0.0  19.214774  132.537258  262.430806  365.362645
1989  0.0  0.0  0.0  0.0  0.0  20.170355  143.107613  288.595548  401.791968
1990  0.0  0.0  0.0  0.0  0.0   7.007194   83.786677  195.970419  302.498290
1991  0.0  0.0  0.0  0.0  0.0   9.453548   90.979226  197.994194  300.336516
1992  0.0  0.0  0.0  0.0  0.0  21.137387  143.053484  274.076452  380.466839
1993  0.0  0.0  0.0  0.0  0.0  16.189323  114.337742  235.376452  347.303968
1994  0.0  0.0  0.0  0.0  0.0   7.848516   82.379710  190.067548  297.121871
1995  0.0  0.0  0.0  0.0  0.0   7.701710   83.505645  194.900742  299.699097
1996  0.0  0.0  0.0  0.0  0.0   9.004000   90.396516  197.489000  295.494548
1997  0.0  0.0  0.0  0.0  0.0   8.527710   90.154129  212.602194  327.981129
1998  0.0  0.0  0.0  0.0  0.0  22.222935  156.149839  306.661290  422.977226
1999  0.0  0.0  0.0  0.0  0.0   5.003355   68.410290  167.707581  267.660226
2000  0.0  0.0  0.0  0.0  0.0   8.095903   83.553871  188.203065  293.920839
2001  0.0  0.0  0.0  0.0  0.0   9.789355   92.961935  205.330258  310.409129
2002  0.0  0.0  0.0  0.0  0.0  11.776935  103.328194  223.026935  329.592387
2003  0.0  0.0  0.0  0.0  0.0   9.833871   93.849226  213.320516  329.414710
2004  0.0  0.0  0.0  0.0  0.0   8.402226   90.005355  211.701935  323.520032
2005  0.0  0.0  0.0  0.0  0.0  26.761968  166.388806  303.939226  405.450935
2006  0.0  0.0  0.0  0.0  0.0   5.145387   68.614710  167.181903  260.019065
2007  0.0  0.0  0.0  0.0  0.0  38.536613  220.595129  384.222161  490.834484
2008  0.0  0.0  0.0  0.0  0.0  14.609484  120.641806  251.793000  359.241065
2009  0.0  0.0  0.0  0.0  0.0   7.789387   83.183387  195.945806  305.600387
2010  0.0  0.0  0.0  0.0  0.0   7.143129   82.941000  194.564548  302.002871
2011  0.0  0.0  0.0  0.0  0.0   4.946645   71.048032  177.838581  288.549194
2012  0.0  0.0  0.0  0.0  0.0   8.356484   87.206226  202.633129  311.155548
2013  0.0  0.0  0.0  0.0  0.0   7.317968   87.500839  202.158161  307.275548
2014  0.0  0.0  0.0  0.0  0.0   6.400290   79.469290  195.640065  310.255839
2015  0.0  0.0  0.0  0.0  0.0  10.219290   97.003355  222.729613  339.421935
2016  0.0  0.0  0.0  0.0  0.0  25.746742  169.934968  318.603290  421.139000
2017  0.0  0.0  0.0  0.0  0.0   5.487097   72.513548  179.035032  290.421065
2018  0.0  0.0  0.0  0.0  0.0   5.980839   74.606968  179.732323  283.818774
2019  0.0  0.0  0.0  0.0  0.0   8.873194   91.361097  205.658710  309.394419
2020  0.0  0.0  0.0  0.0  0.0  18.601710  141.123161  278.864323  400.142387
2021  0.0  0.0  0.0  0.0  0.0   4.634581   69.529935  172.783613  276.725355
2022  0.0  0.0  0.0  0.0  0.0  10.197065   98.317613  218.686613  327.063387
2023  0.0  0.0  0.0  0.0  0.0   9.316903   91.635032  210.327710  325.150548

                  ...          12                                          \
              9   ...          14          15          16         17   18
1981  423.734194  ...  294.257871  182.940355   75.982806   6.009419  0.0
1982  500.903742  ...  367.507645  238.377226  106.387290  11.660161  0.0
1983  498.369516  ...  407.763839  299.159935  155.497742  24.016161  0.0
1984  452.114000  ...  288.062613  177.452161   76.576903   6.915323  0.0
1985  531.450871  ...  368.069613  248.638677  115.393452  13.254387  0.0
1986  459.902581  ...  470.760032  361.501516  208.000452  33.376452  0.0
1987  448.943710  ...  378.264419  267.714903  130.550484  16.594000  0.0
1988  441.128581  ...  356.026742  238.496032  112.310258  12.768129  0.0
1989  473.397516  ...  411.976581  305.003000  157.668742  23.523774  0.0
1990  387.229452  ...  287.027677  180.467065   79.075032   6.721323  0.0
1991  381.527484  ...  394.173968  276.506677  136.019613  18.852806  0.0
1992  451.223710  ...  350.463806  239.723935  115.954484  14.778194  0.0
1993  424.712323  ...  383.425419  279.121613  141.664839  20.903258  0.0
1994  384.025839  ...  344.229387  228.677355  103.537355  12.492419  0.0
1995  379.103323  ...  321.232742  210.156903   93.919258  10.082323  0.0
1996  372.184548  ...  264.646097  161.464419   67.592419   6.167548  0.0
1997  415.634065  ...  296.839097  187.717032   82.496903   8.085097  0.0
1998  496.203419  ...  354.631581  243.652387  117.806935  14.581742  0.0
1999  349.075226  ...  266.245613  161.544226   66.082258   3.968323  0.0
2000  377.699871  ...  433.541065  325.159355  171.341452  24.599097  0.0
2001  394.371000  ...  371.443032  244.182935  111.579290  10.723742  0.0
2002  407.073839  ...  280.124226  177.850548   78.531710   7.448968  0.0
2003  417.497452  ...  304.386387  191.224613   77.561452   5.989419  0.0
2004  411.967774  ...  279.996774  172.301839   69.972323   5.581032  0.0
2005  474.229839  ...  250.248323  152.225000   62.741645   4.078710  0.0
2006  340.555581  ...  348.953000  232.037387  107.308613  10.750226  0.0
2007  556.658774  ...  279.611839  169.100935   71.442258   5.775806  0.0
2008  433.330968  ...  332.046452  216.059806   94.310419   9.117000  0.0
2009  394.285065  ...  347.692258  232.302968  106.574097  11.312484  0.0
2010  395.666097  ...  249.476839  146.422710   56.582097   3.208710  0.0
2011  385.141581  ...  314.248806  201.079516   87.519226   8.494097  0.0
2012  394.413065  ...  281.896806  174.892129   72.910935   5.769645  0.0
2013  387.179774  ...  275.760645  177.094774   78.200742   7.893677  0.0
2014  397.856452  ...  266.061710  161.995065   64.384452   4.203000  0.0
2015  423.001774  ...  299.041613  188.934290   79.617581   7.040806  0.0
2016  486.544903  ...  277.594355  168.774742   67.378484   4.562226  0.0
2017  383.440581  ...  325.026645  212.727452   96.344935  10.829032  0.0
2018  372.502258  ...  282.645419  173.748452   71.578774   5.857032  0.0
2019  386.952548  ...  300.200710  194.129903   84.147548   7.610677  0.0
2020  480.239323  ...  291.535516  184.428710   77.045129   6.283161  0.0
2021  364.595194  ...  292.529032  187.676097   79.672065   6.627065  0.0
2022  409.672774  ...  328.190419  219.290581  100.610581  10.797710  0.0
2023  416.306387  ...  338.516903  222.772710   97.167323   9.885129  0.0


       19   20   21   22   23
1981  0.0  0.0  0.0  0.0  0.0
1982  0.0  0.0  0.0  0.0  0.0
1983  0.0  0.0  0.0  0.0  0.0
1984  0.0  0.0  0.0  0.0  0.0
1985  0.0  0.0  0.0  0.0  0.0
1986  0.0  0.0  0.0  0.0  0.0
1987  0.0  0.0  0.0  0.0  0.0
1988  0.0  0.0  0.0  0.0  0.0
1989  0.0  0.0  0.0  0.0  0.0
1990  0.0  0.0  0.0  0.0  0.0
1991  0.0  0.0  0.0  0.0  0.0
1992  0.0  0.0  0.0  0.0  0.0
1993  0.0  0.0  0.0  0.0  0.0
1994  0.0  0.0  0.0  0.0  0.0
1995  0.0  0.0  0.0  0.0  0.0
1996  0.0  0.0  0.0  0.0  0.0
1997  0.0  0.0  0.0  0.0  0.0
1998  0.0  0.0  0.0  0.0  0.0
1999  0.0  0.0  0.0  0.0  0.0
2000  0.0  0.0  0.0  0.0  0.0
2001  0.0  0.0  0.0  0.0  0.0
2002  0.0  0.0  0.0  0.0  0.0
2003  0.0  0.0  0.0  0.0  0.0
2004  0.0  0.0  0.0  0.0  0.0
2005  0.0  0.0  0.0  0.0  0.0
2006  0.0  0.0  0.0  0.0  0.0
2007  0.0  0.0  0.0  0.0  0.0
2008  0.0  0.0  0.0  0.0  0.0
2009  0.0  0.0  0.0  0.0  0.0
2010  0.0  0.0  0.0  0.0  0.0
2011  0.0  0.0  0.0  0.0  0.0
2012  0.0  0.0  0.0  0.0  0.0
2013  0.0  0.0  0.0  0.0  0.0
2014  0.0  0.0  0.0  0.0  0.0
2015  0.0  0.0  0.0  0.0  0.0
2016  0.0  0.0  0.0  0.0  0.0
2017  0.0  0.0  0.0  0.0  0.0
2018  0.0  0.0  0.0  0.0  0.0
2019  0.0  0.0  0.0  0.0  0.0
2020  0.0  0.0  0.0  0.0  0.0
2021  0.0  0.0  0.0  0.0  0.0
2022  0.0  0.0  0.0  0.0  0.0
2023  0.0  0.0  0.0  0.0  0.0

[43 rows x 288 columns]

- Taking the transformed data and saving it to an Excel file for further analysis

In [33]:
month_to_name = {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}

monthly_means.xs(1, level=0, axis=1).to_excel('transformed_data/monthly_means_jakarta.xlsx', sheet_name='January')
for month in range(2, 13):
    # write to the same excel file
    with pd.ExcelWriter('transformed_data/monthly_means_jakarta.xlsx', engine='openpyxl', mode='a') as writer:
        monthly_means.xs(month, level=0, axis=1).to_excel(writer, sheet_name=month_to_name[month])

## Six Sigma Analysis

In [35]:
test = pd.read_excel('transformed_data/monthly_means_jakarta.xlsx', sheet_name='January', index_col=0) 
test.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
1981,0,0,0,0,0,13.554581,112.441774,237.408774,348.555516,423.734194,...,310.780903,190.580129,76.698935,5.710097,0,0,0,0,0,0
1982,0,0,0,0,0,16.494387,138.053000,291.210839,418.658194,500.903742,...,371.451323,243.908032,109.234581,11.550677,0,0,0,0,0,0
1983,0,0,0,0,0,24.469452,168.826968,313.077968,426.619194,498.369516,...,392.585903,276.354419,133.866806,17.774323,0,0,0,0,0,0
1984,0,0,0,0,0,14.537161,121.603677,256.989516,370.498903,452.114000,...,337.175194,209.575806,90.121161,8.100129,0,0,0,0,0,0
1985,0,0,0,0,0,31.068581,190.038355,352.806613,466.454452,531.450871,...,440.949129,315.470806,154.613161,22.922516,0,0,0,0,0,0

- Making six sigma plots for every hour of every month and finding outliers
- Storing the visualizations in ```visualizations``` folder

In [49]:
import numpy as np
import matplotlib.pyplot as plt

def make_sigma_plot(data, col, month):
    mean = data[col].mean()
    std = data[col].std()

    data[col].plot()
    plt.axhline(mean, color='r')
    plt.axhline(mean + 3*std, color='g')
    plt.axhline(mean - 3*std, color='g')

    outliers = data[col][(data[col] > mean + 3*std) | (data[col] < mean - 3*std)]   

    for i in outliers.index:
        plt.text(i, outliers[i], str(i))

    plt.title(f'{col}th hour')
    plt.xlabel('Year')
    plt.ylabel('Electricity (in kW)')
    plt.savefig(f'visualizations/sigma_plots/{month}_{col}th_hour.png')
    plt.close()


sheet_names = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

for sheet in sheet_names:
    data = pd.read_excel('transformed_data/monthly_means_jakarta.xlsx', sheet_name=sheet, index_col=0)
    for col in data.columns:
        make_sigma_plot(data, col, sheet)

## Box Plots

- Making box plots for every month
- Storing the visualizations in ```visualizations``` folder

In [51]:
def make_box_plot(data, month):
    plt.figure(figsize=(10, 6))
    data.boxplot()
    plt.title(f'Electricity production by hour {month}')
    plt.ylabel('Electricity (in kW)')
    plt.savefig(f'visualizations/box_plots/{month}.png')
    plt.close()

for sheet in sheet_names:
    data = pd.read_excel('transformed_data/monthly_means_jakarta.xlsx', sheet_name=sheet, index_col=0)
    make_box_plot(data, sheet)

## ANOVA

- Performing ANOVA on the data to check if the means of the data (for a given hour and given month) are different for different years
- Storing the results in ```results``` folder

In [67]:
from scipy.stats import f_oneway

def anova_test(data):
    f, p = f_oneway(*data)
    return f, p

data_anova = {}

for month in range(1, 13):
    data_anova[month] = []
    for hour in range(24):
        data = [list(data_jakarta[(data_jakarta['local_time'].dt.year == year) & (data_jakarta['local_time'].dt.month == month) & (data_jakarta['local_time'].dt.hour == hour)]['electricity']) for year in range(1981, 2024)]
        f, p = anova_test(data)
        data_anova[month].append([f, p])

data_anova = pd.DataFrame(data_anova, index=range(24))

data_anova.head()

C:\Users\Ayush\AppData\Roaming\Python\Python311\site-packages\scipy\stats\_stats_py.py:4167: ConstantInputWarning: Each of the input arrays is constant;the F statistic is not defined or infinite
  warnings.warn(stats.ConstantInputWarning(msg))

,1,2,3,4,5,6,7,8,9,10,11,12
0,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
1,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
2,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
3,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
4,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"

In [68]:
data_anova

,1,2,3,4,5,6,7,8,9,10,11,12
0,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
1,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
2,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
3,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
4,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
5,"[6.94301834428495, 1.7147945599396631e-34]","[5.027367707017519, 5.420750971015413e-22]","[7.349056578897029, 4.234343733356774e-37]","[8.82065644507188, 2.927906080601795e-46]","[9.632694519085982, 1.3647562338278297e-51]","[13.013664949050899, 8.819999053903468e-72]","[5.8306866209395025, 2.455108095042135e-27]","[4.698417290348826, 4.2133434048082593e-20]","[6.467766101069243, 2.565618853390248e-31]","[15.030712846831618, 5.235174732226169e-84]","[8.307227539065863, 5.009482261114157e-43]","[6.697144144873622, 6.537310611915423e-33]"
6,"[6.844961694178698, 7.32225450273887e-34]","[5.58158471048145, 1.7415363147298838e-25]","[7.824432122986262, 3.826432842917376e-40]","[8.394520326565445, 1.4083871986160861e-43]","[12.003002182472983, 3.5448795602840737e-66]","[15.8141441251009, 7.605804057672393e-88]","[8.376552522599829, 1.1560500758899462e-43]","[6.2082336300291185, 9.155479679835258e-30]","[9.19564762417627, 1.312192941848888e-48]","[16.517484166322106, 1.9877132817353825e-92]","[9.312527352104178, 2.4453776360300798e-49]","[6.366583121474441, 8.761680661889447e-31]"
7,"[6.248883075452877, 5.012857937728326e-30]","[5.295098852508036, 1.119522970076378e-23]","[7.627475132053044, 6.960589704458404e-39]","[7.542109125319258, 3.555912726964163e-38]","[11.815055849136217, 4.859503535276165e-65]","[16.295980181478512, 1.5753149187874927e-90]","[8.753301568665838, 4.705807993289973e-46]","[6.305410429304327, 2.1691565380653623e-30]","[11.734446064403071, 3.54793853834632e-64]","[16.87012796588481, 2.1528238508347268e-94]","[9.78819732825677, 2.6976146292388907e-52]","[6.035325112006105, 1.1863102865188107e-28]"
8,"[5.805952152339091, 3.540255037925565e-27]","[5.078983650886909, 2.5683342526845046e-22]","[7.336955420904917, 5.063009633315405e-37]","[7.306181403350911, 1.130862922823662e-36]","[11.435131701661632, 9.897195599145223e-63]","[15.98129713682526, 8.861088636515929e-89]","[8.87631994399753, 7.8404316509873675e-47]","[6.1982302763853605, 1.0618289602229386e-29]","[13.474288875394903, 1.7705863797743324e-74]","[16.077471262417586, 5.857186215427657e-90]","[9.436526993160019, 4.125836945614126e-50]","[5.477246100589381, 4.560708516471537e-25]"
9,"[5.2753775981182836, 8.947033577082484e-24]","[4.713636549004377, 5.011473067635452e-20]","[6.959993960880308, 1.333816397176391e-34]","[6.9613493979475125, 1.7934093527081991e-34]","[10.907617543519423, 1.6768236729627855e-59]","[15.291884480870138, 6.552726571633144e-85]","[8.763741620600314, 4.0414764701043536e-46]","[6.030712874205864, 1.270186149242452e-28]","[13.838192680362505, 1.3568260561623529e-76]","[14.171381801593455, 4.855632777155258e-79]","[8.73003449810793, 1.0859209215489453e-45]","[4.7618051223802595, 1.6715335415814786e-20]"
10,"[4.855673053131122, 4.2411928335380045e-21]","[4.436647181796083, 2.659845277961355e-18]","[6.396779623863871, 5.600715530481417e-31]","[6.6195755081170224, 2.742488700683566e-32]","[10.411530861748156, 1.9278011912436452e-56]","[14.385781993840164, 9.432410544568143e-80]","[8.504939630230796, 1.7672164275117288e-44]","[6.028530320054992, 1.3119186568795886e-28]","[12.84080972696787, 9.189515021107705e-71]","[12.509611469750777, 3.178465366647439e-69]","[8.14417852372754, 5.376640661544495e-42]","[4.233524493918841, 3.531876011629223e-17]"
11,"[4.442439901756834, 1.735416175334971e-18]","[4.125829821279853, 2.2080660786988998e-16]","[6.054269672347779, 8.960443776188617e-29]","[6.555782822215028, 7.017061804986787e-32]","[10.208514763343347, 3.500183445152527e-55]","[13.890765963552136, 6.72986042183782e-77]","[8.107049283498885, 6.00835929852316e-42]","[6.203796304377917, 9.77768959568539e-30]","[12.5255865565658, 6.718686694631311e-69]","[12.401620386225742, 1.4114868085312885e-68]","[8.055807986312109, 1.9493381136223853e-41]","[4.0354716369409545, 6.014280137986599e-16]"
12,"[4.687633382375663, 4.9303121342848195e-20]","[4.436633388595386, 2.6603695029360767e-18]","[6.019527482632854, 1.4990554022958373e-28]","[6.748145356937964, 4.130975738407448e-33]","[10.523970440336983, 3.884838432666087e-57]","[13.948410766856473, 3.1220357873660267e-77]","[8.097468233348964, 6.91572332724558e-42]","[6.423046434109332, 3.7948266090497365e-31]","[12.676244553141478, 8.612736048290818e-70]","[13.950857448894636, 9.395436817945224e-78]","[8.553838172993354, 1.3943393228093362e-44]","[4.386245943343393, 3.9110239727087585e-18]"
13,"[5.36335574839517, 2.4472680833482084e-24]","[5.005543356727171, 7.4328122692874155e-22]","[6.3908963731227635, 6.110938523315415e-31]","[7.286539072933673, 1.508739941725622e-36]","[11.116257748234428, 8.794209807243223e-61]","[14.113327750136193, 3.4834279602643725e-78]","[8.179461158421624, 2.076320947187439e-42]","[6.242036666787332, 5.548118379854306e-30]","[11.907876512211262, 3.2305198614960413e-65]","[15.52102553471425, 8.274994561907396e-87]","[9.355200549022411, 1.3250583119760358e-49]","[5.012456156189775, 4.2670467547450445e-22]"
14,"[6.098250343447062, 4.670683156326343e-29]","[5.5791435094924555, 1.804495145118865e-25]","[6.872985976064111, 4.835544393421564e-34]","[7.724538183549593, 2.4610475935321752e-39]","[11.539210541744845, 2.2992955003217515e-63]","[13.922633846848406, 4.401055671464189e-77]","[8.03195023261054, 1.8100116481064376e-41]","[6.138526541772968, 2.5717980325807684e-29]","[10.270481468299028, 2.8391420747376887e-55]","[16.55471144885464, 1.2311375853101174e-92]","[9.724095247159475, 6.735345036579166e-52]","[5.617185582566654, 5.7729506876284e-26]"
15,"[6.3220986435074416, 1.6938987682938817e-30]","[5.871955680172726, 2.5416635951596368e-27]","[7.4984416364177475, 4.6673533981903046e-38]","[8.425248938327677, 9.012879434447199e-44]","[11.847472934206667, 3.0919722897186946e-65]","[13.77371076203681, 3.2092752501855996e-76]","[7.937022812095912, 7.303603217814279e-41]","[5.935982980788294, 5.165716993307415e-28]","[8.257640187170294, 1.0305503570720421e-42]","[16.5208563271827, 1.903279681359761e-92]","[9.427697118639774, 4.682751814184709e-50]","[6.403267291270145, 5.08732125598663e-31]"
16,"[6.467582486562276, 1.9613965745530681e-31]","[5.894489663136568, 1.8305108069334895e-27]","[7.747121818245534, 1.194192518188449e-39]","[8.635791590346027, 4.250628177888773e-45]","[10.816973197219937, 6.053364178977007e-59]","[14.263712353686927, 4.741659080189118e-79]","[7.7884301241142095, 6.500271501660439e-40]","[5.93240335957031, 5.446894149446477e-28]","[6.579583733924538, 4.942197099719058e-32]","[14.79025553640452, 1.26307902664522e-82]","[8.46752362437075, 4.878368637961826e-44]","[7.080709036895776, 2.2356259444375427e-35]"
17,"[6.417979470569823, 4.090745742832056e-31]","[5.119305088158622, 1.4324155670662305e-22]","[7.666583688080217, 3.911342458539225e-39]","[9.068873609272233, 8.141478271953117e-48]","[7.1560254292368946, 7.339347449855324e-36]","[9.34090914090601, 1.6268191235137316e-49]","[4.798351962301961, 9.802923612037602e-21]","[4.863503797170779, 3.7822088218446816e-21]","[5.245817372311243, 1.6425373805502518e-23]","[12.345848941892696, 3.051460766569494e-68]","[7.652750259966758, 7.035786742207677e-39]","[7.113885337235491, 1.368647070919157e-35]"
18,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
19,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
20,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
21,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
22,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"
23,"[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]","[nan, nan]"

In [69]:
data_anova.to_excel('results/anova_results_jakarta.xlsx')